/**
 * Hideo
 * https://github.com/paazmaya/hideo
 *
 * Generate report for visual regression testing
 *
 * Copyright (c) Juga Paazmaya <paazmaya@yahoo.com> (https://paazmaya.fi)
 * Licensed under the MIT license
 */

'use strict';

const fs = require('fs'),
  path = require('path');

const generateSection = require('./generate-section');
/*
{
  "cdfaebb483965949b1049c52c77d8ed3": {
    "metric": "PeakSignalToNoiseRatio",
    "psnr": {
      "red": "17.78",
      "green": "18.50",
      "blue": "18.87",
      "total": "18.36"
    },
    "A": "tests/fixtures/prev/naginata.fi-header-navigation.png",
    "B": "tests/fixtures/curr/naginata.fi-header-navigation.png",
    "diff": "tests/fixtures/diff/naginata.fi-header-navigation.png"
  }
}

*/
module.exports = (data, directory) => {
  const today = new Date().toISOString().split('T').shift();
  let html = '<!doctype html>'; // TODO: Change to buffer once big use case exists for measurement
  html += `
  <html>
  <head>
    <title>Visual Regression testing report ${today}</title>
    <style></style>
    <link href="hideo.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>Visual Regression testing report ${today}</h1>
    </header>
  `;

  Object.keys(data).forEach((key) => {
    html += generateSection(key, data[key], directory);
  });

  html += `
    <footer role="contentinfo">
      Generated by <strong>hideo</strong> in ${today}
    </footer>

    <script>
    </script>
  </body>
</html>

`;

  return html;
};
